apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nats-connector
    component: nats-connector
  name: nats-connector
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-connector
      component: nats-connector
  template:
    metadata:
      labels:
        app: nats-connector
        component: nats-connector
    spec:
      containers:
      - name: nats-connector
        image: ghcr.io/openfaas/nats-connector:0.2.4
        env:
          - name: upstream_timeout
            value: "1m1s"
          - name: gateway_url
            value: "http://gateway.openfaas:8080"
          - name: topics
            value: "nats-test,"
          - name: print_response
            value: "true"
          - name: print_response_body
            value: "true"
          - name: basic_auth
            value: "true"
          - name: secret_mount_path
            value: "/var/secrets/"
          - name: topic_delimiter
            value: ","
          - name: asynchronous_invocation
            value: "false"
        volumeMounts:
            - name: auth
              readOnly: true
              mountPath: "/var/secrets/"
      volumes:
      - name: auth
        secret:
          secretName: basic-auth
